import type { TimelineEvent } from "./timeline.types";

export const IRAN_MANUAL_TIMELINE: TimelineEvent[] = [
  {
    id: "2025-06-13-israel-strikes",
    ts: Date.parse("2025-06-13T12:00:00Z"),
    title: "Israel launches major strikes on Iranian nuclear & military targets",
    summary:
      "Israel launches major air strikes; Iran responds within hours with missile and drone attacks.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["Israel", "Iran", "Strikes"],
    kind: "manual",
  },
  {
    id: "2025-06-22-us-strikes-nuclear-sites",
    ts: Date.parse("2025-06-22T12:00:00Z"),
    title: "US strikes Iranian nuclear facilities (Natanz, Fordow, Isfahan)",
    summary:
      "US strikes nuclear facilities; Trump says the program was degraded. Iran says set back but not destroyed.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["US", "Iran", "Nuclear"],
    kind: "manual",
  },
  {
    id: "2025-06-23-iran-retaliation-al-udeid",
    ts: Date.parse("2025-06-23T12:00:00Z"),
    title: "Iran retaliates with missiles toward Al Udeid airbase in Qatar",
    summary:
      "Iran fires missiles toward Al Udeid; missiles intercepted; no casualties reported.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["Iran", "Qatar", "US Base"],
    kind: "manual",
  },
  {
    id: "2025-06-24-ceasefire",
    ts: Date.parse("2025-06-24T12:00:00Z"),
    title: "US-brokered ceasefire ends the June 2025 war after 12 days",
    summary:
      "Ceasefire takes effect after 12 days of fighting, ending hostilities between Iran and Israel.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["Ceasefire", "Iran", "Israel"],
    kind: "manual",
  },
  {
    id: "2025-07-02-iran-iaea-halt",
    ts: Date.parse("2025-07-02T12:00:00Z"),
    title: "Iran signs law halting cooperation with the IAEA",
    summary:
      "Iran halts IAEA cooperation and restricts inspectors unless specifically authorized by Iran’s security council.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["IAEA", "Iran", "Nuclear"],
    kind: "manual",
  },
  {
    id: "2025-08-28-un-sanctions-triggered",
    ts: Date.parse("2025-08-28T12:00:00Z"),
    title: "European states trigger mechanism reinstating UN sanctions",
    summary:
      "European states trigger a mechanism reinstating UN sanctions on Iran for the first time in a decade.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["UN", "Sanctions", "Iran"],
    kind: "manual",
  },
  {
    id: "2025-12-28-protests-rial",
    ts: Date.parse("2025-12-28T12:00:00Z"),
    title: "Protests erupt as Iran’s rial plunges and prices spike",
    summary:
      "Protests break out in major cities over soaring prices after the rial plunges against the US dollar.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["Economy", "Protests", "Iran"],
    kind: "manual",
  },
  {
    id: "2026-01-08-internet-shutdown",
    ts: Date.parse("2026-01-08T12:00:00Z"),
    title: "Iran-wide internet shutdown amid antigovernment protests",
    summary:
      "Internet is shut down across Iran following the outbreak and spread of antigovernment protests.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["Internet", "Protests", "Iran"],
    kind: "manual",
  },
  {
    id: "2026-01-13-trump-protests-military-build",
    ts: Date.parse("2026-01-13T12:00:00Z"),
    title: "Trump urges protests; US begins bolstering forces near Iran",
    summary:
      "Trump tells Iranians to keep protesting; US begins bolstering its military presence off Iran.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["US", "Iran", "Forces"],
    kind: "manual",
  },
  {
    id: "2026-02-06-indirect-talks",
    ts: Date.parse("2026-02-06T12:00:00Z"),
    title: "US–Iran indirect nuclear negotiations begin (Oman-mediated)",
    summary:
      "Indirect negotiations begin in Geneva, mediated by Oman, aimed at reaching a deal on Iran’s nuclear program.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["Talks", "Oman", "Nuclear"],
    kind: "manual",
  },
  {
    id: "2026-02-26-third-round-talks",
    ts: Date.parse("2026-02-26T12:00:00Z"),
    title: "Third round of nuclear talks concludes; mediator cites progress",
    summary:
      "Third round concludes; mediator says significant progress and more talks planned the following week.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["Talks", "Geneva", "Oman"],
    kind: "manual",
  },
  {
    id: "2026-02-28-israel-strikes-iran-retaliates",
    ts: Date.parse("2026-02-28T12:00:00Z"),
    title: "Israel launches coordinated strikes; Iran retaliates across the region",
    summary:
      "Israel launches coordinated strikes on Iranian targets; Iran retaliates with air and missile strikes across the region.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2026/2/28/us-israel-bomb-iran-a-timeline-of-talks-and-threats-leading-up-to-attacks",
    tags: ["Escalation", "Iran", "Israel"],
    kind: "manual",
  },
  {
    id: "2026-03-04-qatar-denies-iran-claim",
    ts: Date.parse("2026-03-04T12:00:00Z"),
    title: "Iran FM says strikes targeted US, not Qatar; Doha rejects claim",
    summary:
      "Iran’s foreign minister says strikes targeted the US, not Qatar; Doha rejects the claim.",
    source: "Reuters",
    url: "https://www.reuters.com/world/middle-east/iran-fm-says-strikes-targeted-us-not-qatar-doha-rejects-claim-2026-03-04/",
    tags: ["Qatar", "US", "Iran"],
    kind: "manual",
  },
  {
    id: "2026-03-05-us-houthi-strikes",
    ts: Date.parse("2026-03-05T03:10:00Z"),
    title: "US strikes Houthi missile infrastructure as Red Sea crisis deepens",
    summary:
      "US forces conducted strikes on missile and drone launch capabilities amid ongoing attacks on commercial shipping routes.",
    source: "Reuters",
    url: "https://www.reuters.com/world/middle-east/",
    tags: ["Houthis", "Red Sea", "missile strikes"],
    kind: "manual",
  },
  {
    id: "2026-03-05-who-hospitals-hit",
    ts: Date.parse("2026-03-05T12:00:00Z"),
    title: "WHO reports hospitals and health facilities hit during attacks",
    summary:
      "WHO reports at least 13 hospitals and health facilities in Iran struck since attacks began; verification ongoing.",
    source: "The Guardian",
    url: "https://www.theguardian.com/global-development/2026/mar/05/at-least-dozen-hospital-and-health-facilities-in-iran-hit-since-us-israel-attacks-began-who-says",
    tags: ["Civilian", "Hospitals", "WHO"],
    kind: "manual",
  },
  {
    id: "2026-03-06-israel-strikes-syria",
    ts: Date.parse("2026-03-06T05:20:00Z"),
    title: "Israeli strikes target Iranian-linked positions in Syria",
    summary:
      "Air operations reportedly hit logistics depots and weapons storage sites connected to Iranian-backed forces near Damascus and eastern Syria.",
    source: "Reuters",
    url: "https://www.reuters.com/world/middle-east/",
    tags: ["Syria", "airstrike", "IRGC"],
    kind: "manual",
  },
  {
    id: "2026-03-07-hormuz-threat-warning",
    ts: Date.parse("2026-03-07T10:45:00Z"),
    title: "Iran warns of possible Hormuz action if pressure escalates",
    summary:
      "Iranian officials suggested continued military pressure could lead to responses affecting maritime transit in the Strait of Hormuz.",
    source: "Reuters",
    url: "https://www.reuters.com/business/aerospace-defense/iran-could-disrupt-strait-hormuz-with-drones-months-2026-03-04/",
    tags: ["Hormuz", "oil supply risk", "escalation"],
    kind: "manual",
  },
  {
    id: "2026-03-08-red-sea-disruptions",
    ts: Date.parse("2026-03-08T16:30:00Z"),
    title: "Red Sea shipping disruptions continue amid Houthi attacks",
    summary:
      "Missile and drone threats linked to Houthi forces forced additional commercial vessels to reroute, increasing global logistics costs and transit times.",
    source: "Reuters",
    url: "https://www.reuters.com/world/middle-east/",
    tags: ["Red Sea", "Houthis", "shipping disruption"],
    kind: "manual",
  },
  {
    id: "2026-03-09-regional-mobilization",
    ts: Date.parse("2026-03-09T12:00:00Z"),
    title: "Regional militaries increase readiness amid escalation fears",
    summary:
      "Several Middle Eastern states raised alert levels and reinforced air defense posture as cross-border strike cycles intensified.",
    source: "Reuters",
    url: "https://www.reuters.com/world/middle-east/",
    tags: ["mobilization", "air defense", "readiness"],
    kind: "manual",
  },
  {
    id: "2026-03-10-us-israel-strikes-expand",
    ts: Date.parse("2026-03-10T09:00:00Z"),
    title: "US–Israel operations expand targeting Iranian-linked networks",
    summary:
      "Military actions reportedly focused on degrading missile, drone, and logistics capabilities associated with Iranian-backed forces across multiple regional theaters.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/news/liveblog/2026/3/10/iran-war-live-trump-says-conflict-will-be-over-soon-40-killed-in-tehran",
    tags: ["strikes", "IRGC", "militia networks", "escalation"],
    kind: "manual",
  },
  {
    id: "2026-03-11-oil-shipping-volatility",
    ts: Date.parse("2026-03-11T14:00:00Z"),
    title: "Oil and shipping markets react to widening conflict risk",
    summary:
      "Energy prices and maritime insurance costs moved higher as traders priced in potential disruption to Gulf shipping routes and infrastructure.",
    source: "Reuters",
    url: "https://www.reuters.com/world/middle-east/number-iranian-missiles-drones-fired-gulf-countries-2026-03-10/",
    tags: ["oil", "shipping", "markets", "Hormuz risk"],
    kind: "manual",
  },
  {
    id: "2026-03-12-us-monitoring-sleeper-cells",
    ts: Date.parse("2026-03-12T18:00:00Z"),
    title: "US officials warn of potential Iranian-linked threats domestically",
    summary:
      "Senior US leadership stated law enforcement and intelligence agencies are monitoring potential Iranian-linked threat networks amid rising Middle East tensions.",
    source: "The Guardian",
    url: "https://www.theguardian.com/us-news/2026/mar/12/california-iran-threat-fbi",
    tags: ["US homeland security", "terror threat", "Iran tensions"],
    kind: "manual",
  },
  {
    id: "2026-03-13-iran-drones-gulf",
    ts: Date.parse("2026-03-13T06:30:00Z"),
    title: "Iran-linked drone activity reported near Gulf infrastructure",
    summary:
      "Regional security sources reported suspected Iranian-linked drone launches toward strategic infrastructure sites across parts of the Gulf. Air defenses were activated in multiple locations as tensions remained elevated.",
    source: "Reuters",
    url: "https://www.reuters.com/world/middle-east/tracking-iranian-attacks-civilian-ships-gulf-2026-03-12/",
    tags: ["drones", "Gulf", "air defense", "escalation"],
    kind: "manual",
  },
];
